services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-aura}
  broker:
    image: rabbitmq:4-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  cache:
    image: valkey/valkey:8-alpine
    restart: always
    ports:
      - 6379:6379
