services:
  aura_db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aura_db
    volumes:
      - ${HOME}/.var/postgresql/aura_db/data:/var/lib/postgresql/data
  aura_broker:
    image: rabbitmq:4-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  aura_cache:
    image: valkey/valkey:8-alpine
    ports:
      - 6379:6379
